# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_dynamic_libs

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[] + collect_dynamic_libs('winrt'),
    datas=[
        ('version.json', '.'),
        ('assets/엑스아이콘.png', 'assets'),
        ('assets/정리 아이콘.png', 'assets'),
        ('assets/수정 아이콘.png', 'assets'),
        ('assets/아래방향 아이콘.png', 'assets'),
        ('assets/윗방향 아이콘.png', 'assets'),
        ('assets/위화살표.png', 'assets'),
        ('assets/popup_images', 'assets/popup_images'),
        ('assets/FluentSystemIcons-Regular.ttf', 'assets'),
        ('assets/FluentSystemIcons-Filled.ttf', 'assets'),
        ('assets/MaterialIcons-Regular.ttf', 'assets'),
        ('assets/icons.png', 'assets'),
        ('assets/editor.html', 'assets'),
    ],
    hiddenimports=[
        'PyQt5.sip',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtWebChannel',
        'PyQt5.QtWebEngineWidgets',
        'ctypes',
        'ctypes.wintypes',
        'sqlite3',
        'socket',
        'threading',
        'urllib.request',
        'urllib.error',
        'json',
        'tempfile',
        'subprocess',
        'asyncio',
        'winreg',
        'PIL',
        'PIL.Image',
        'PIL.ImageFilter',
        'PIL.ImageOps',
        'google.genai',
        'google.genai.types',
        'httpx',
        'anyio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'django',
        'flask',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SSNnote',
    icon='icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='SSNnote'
)
